# Generated by Django 2.2.12 on 2022-06-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usredetails',
            name='hobbies',
            field=models.CharField(choices=[('Dance', 'Dance'), ('Travling', 'Travling'), ('Reading', 'Reading')], max_length=50),
        ),
    ]
