# Generated by Django 2.2.12 on 2022-06-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usredetails',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usredetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
