# Generated by Django 2.2.12 on 2022-06-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220614_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usredetails',
            name='address',
            field=models.TextField(max_length=500),
        ),
    ]
