# Generated by Django 2.2.12 on 2022-06-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220614_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usredetails',
            name='address',
            field=models.TextField(max_length=150),
        ),
    ]
