# Generated by Django 4.0.4 on 2022-07-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220616_0937'),
        ('account', '0004_auto_20220616_0656'),
    ]

    operations = [
    ]
