# Generated by Django 4.0.4 on 2022-07-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_usredetails_gender_remove_usredetails_hobbies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usredetails',
            old_name='mobile_number',
            new_name='Adhaar_number',
        ),
    ]
