# Generated by Django 4.0.4 on 2022-07-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_mobile_number_usredetails_adhaar_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usredetails',
            name='address',
        ),
    ]
