# Generated by Django 2.2.12 on 2022-07-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_usredetails_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usredetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
