# Generated by Django 2.2.12 on 2022-07-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20220711_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='usredetails',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
